
# Reglas de asociación con apriori

## Utilidades

```{r}
#Librerías
library(here)
library(foreign)
library(arules)
library(dplyr)

# Función CLC
clc <- function() shell("cls")
```

```{r}
vars1 <- c("Logro_Mate",
           "Logro_Lect",
           "Desempeño_Mate",
           "Desempeño_Lect",
           "Cod_Region",
           "Jornada",
           "Cod_Sector",
           "CC_Familia_Automovil",
           "Edad_RECO",
           "Sexo_RECO",
           "Cod_Area",
           "Fm_Grado_Alcanzo_Papa_RECO",
           "Fm_Grado_Alcanzo_Mama_RECO",
           "Sc_Servicio_Internet",
           "Tipo_Eval")

vars2 <- c("Logro_Mate",
           "Logro_Lect",
           "Desempeño_Mate",
           "Desempeño_Lect",
           "Cod_Region",
           "Jornada",
           "sector",
           "CC_Familia_Automovil",
           "Edad_Reco",
           "Sexo_Reco",
           "Cod_Area",
           "Fm_Grado_Alcanzo_Papa_RECO",
           "Fm_Grado_Alcanzo_Mama_RECO",
           "Sc_Servicio_Internet",
           "Tipo_Eval")

vars3 <- c("Logro_Mate",
           "Logro_Lect",
           "Desempeño_Mate",
           "Desempeño_Lect",
           "Cod_Region",
           "Jornada",
           "CC_Familia_Automovil",
           "Edad_Reco",
           "Sexo_Reco",
           "Cod_Area",
           "Fm_Grado_Alcanzo_Papa_RECO",
           "Fm_Grado_Alcanzo_Mama_RECO",
           "CC_Servicio_Internet")

```

```{r}


data_apriori <- data_apriori[data_apriori$Logro_Mate == "Logro" |
                               data_apriori$Logro_Lect == "Logro", ]

```


## Uso del algoritmo apriori

```{r}
reglas <- apriori(data_apriori,
                  parameter = list(support = 0.2, confidence = 0.5))

reglas <- as(reglas, "data.frame")
View(reglas)
```



